a:4:{s:5:"child";a:1:{s:0:"";a:1:{s:3:"rss";a:1:{i:0;a:6:{s:4:"data";s:3:"


";s:7:"attribs";a:1:{s:0:"";a:1:{s:7:"version";s:3:"2.0";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:1:{s:7:"channel";a:1:{i:0;a:6:{s:4:"data";s:51:"
	
	
	
	
	
	
	
	
	
			
		
		
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:3:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:32:"EndNote ved Høgskolen i Gjøvik";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:26:"http://blog.hig.no/endnote";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:13:"lastBuildDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed, 16 Jun 2010 20:28:08 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:9:"generator";a:1:{i:0;a:5:{s:4:"data";s:29:"http://wordpress.org/?v=2.9.2";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"language";a:1:{i:0;a:5:{s:4:"data";s:2:"en";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"item";a:10:{i:0;a:6:{s:4:"data";s:44:"
		
		
		
		
		
				
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"EndNote X4 for Windows lansert";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:69:"http://blog.hig.no/endnote/2010/06/16/endnote-x4-for-windows-lansert/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:78:"http://blog.hig.no/endnote/2010/06/16/endnote-x4-for-windows-lansert/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed, 16 Jun 2010 19:59:19 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:2:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:10:"EndNote X4";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:33:"http://blog.hig.no/endnote/?p=369";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1009:"<p>Som vanlig i juni har Thomson Reuters kommet med en ny EndNote-versjon &#8211; denne gangen er det EndNote X4 for Windows som er lansert.</p>
<p>Som omtalt <a href="http://blog.hig.no/endnote/2010/06/15/endnote-og-word-2010-kompatiblitet/">tidligere</a> er den nye versjonen kompatibel med Microsoft 2010</p>
<p>Av andre nyheter ved denne lanseringen nevner jeg: Import av og søk i pdf-filer, forbedret Cite While Your Write, og forbedring av samarbeidsmuligheter via EndNote Web.</p>
<p>Les hele pressemeldingen her: <a href="http://forums.thomsonscientific.com/t5/EndNote-General/Thomson-Reuters-Releases-EndNote-X4-for-Windows/m-p/11360#M3626">http://forums.thomsonscientific.com/t5/EndNote-General/Thomson-Reuters-Releases-EndNote-X4-for-Windows/m-p/11360#M3626</a></p>
<p>Følger Thomson Reuter og deres samarbeidspartnere det vanlige opplegget for distribusjon, vil vi ha den nye versjonen tilgjengelig for HIG-brukere i august/september. Versjonen for Mac OS X vil bli lansert senere i sommer.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:1009:"<p>Som vanlig i juni har Thomson Reuters kommet med en ny EndNote-versjon &#8211; denne gangen er det EndNote X4 for Windows som er lansert.</p>
<p>Som omtalt <a href="http://blog.hig.no/endnote/2010/06/15/endnote-og-word-2010-kompatiblitet/">tidligere</a> er den nye versjonen kompatibel med Microsoft 2010</p>
<p>Av andre nyheter ved denne lanseringen nevner jeg: Import av og søk i pdf-filer, forbedret Cite While Your Write, og forbedring av samarbeidsmuligheter via EndNote Web.</p>
<p>Les hele pressemeldingen her: <a href="http://forums.thomsonscientific.com/t5/EndNote-General/Thomson-Reuters-Releases-EndNote-X4-for-Windows/m-p/11360#M3626">http://forums.thomsonscientific.com/t5/EndNote-General/Thomson-Reuters-Releases-EndNote-X4-for-Windows/m-p/11360#M3626</a></p>
<p>Følger Thomson Reuter og deres samarbeidspartnere det vanlige opplegget for distribusjon, vil vi ha den nye versjonen tilgjengelig for HIG-brukere i august/september. Versjonen for Mac OS X vil bli lansert senere i sommer.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:74:"http://blog.hig.no/endnote/2010/06/16/endnote-x4-for-windows-lansert/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:1;a:6:{s:4:"data";s:50:"
		
		
		
		
		
				
		
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:34:"Gjøre endringer i importfilteret?";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:76:"http://blog.hig.no/endnote/2010/06/15/gj%c3%b8re-endringer-i-importfilteret/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:85:"http://blog.hig.no/endnote/2010/06/15/gj%c3%b8re-endringer-i-importfilteret/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 15 Jun 2010 18:33:41 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:4:{i:0;a:5:{s:4:"data";s:10:"Opplæring";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:12:"importfiltre";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:7:"medline";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:3;a:5:{s:4:"data";s:4:"ovid";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:33:"http://blog.hig.no/endnote/?p=366";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:3220:"<p>Selv om EndNote stadig vekk lanserer nye importfiltre, kan det likevel være nødvendig å gjøre endringer for å redusere &#8220;vaskingen&#8221; av importerte data. Etter at EndNote kom med oppdaterte versjoner av importfiltre for OVID-basene, fikk jeg lyst til å teste ut filteret for import av referanser fra Medline via Ovid. Etter å ha gjennomført en uproblematisk import fikk jeg dette resultatet i visningsstilen APA:</p>
<p>Barnard, A., Nash, R., &amp; O&#8217;Brien, M. (2005). Information literacy: developing lifelong skills through nursing education.  [Review]. <em>Journal of Nursing Education, 44</em>(11), 505-510.</p>
<p>I det store og hele ser jo dette fint ut, bortsett fra detaljen som sier at artikkelen er fagfellevurdert ([Review]). I EndNote kan dette filtreres ut på to måter – enten ved at du endrer i visningsstilen (out-put styles) slik at dataene i feltet ”Type of Article” ikke vises, eller ved at du endrer importfilteret slik at dataene som ligger i feltet ”Type of Article” ikke blir med når du foretar importen.</p>
<p>Om du velger den ene eller den andre metoden så må du vite at det valget du foretar har noen konsekvenser. Endrer du i visningsstilen vil dataene i feltet ”Type of Article” fortsatt være intakte i EndNote-biblioteket slik at du for eksempel senere kan søke fram ”Review-artiklene”. For å få dette riktig i forhold til APA-stilens krav (hvor dette normalt ikke skal vises), må du altså endre visningsstilen. Hvis du derimot fjerner dataene ved importen slik at du ikke trenger å endre visningsstilen, vil du naturligvis ikke kunne søke fram fagfellevurderte artikler hvis det er ønskelig. Har du heller ikke bruk for dette, kan du endre importfilteret slik at du får følgende resultat etter importen:</p>
<p>Barnard, A., Nash, R., &amp; O&#8217;Brien, M. (2005). Information literacy: developing lifelong skills through nursing education. <em>Journal of Nursing Education, 44</em>(11), 505-510.</p>
<p>Fremgangsmetoden er slik: Stå i EndNote og velg &lt;Edit&gt;, &lt;Import Filters&gt;, &lt;Open Filter Manager &#8230;&gt;. Finn fram til Medline-filteret fra OvidSP, marker det og klikk &#8220;Edit&#8221;. I vinduet du får opp velger du &#8220;Templates&#8221; i menyen til høyre, og her se du nå de ulike feltene som en importert post kan bestå av. Leter du nedover, kommer du etter hvert til et felt hvor taggen heter &#8220;PT &#8211; &#8221; med tilhørende &#8220;Field(s)&#8221; hvor det står &#8220;Type of Article&#8221;.</p>
<p><a href="http://blog.hig.no/endnote/files/2010/06/import_filter.jpg"><img class="aligncenter size-large wp-image-365" title="import_filter" src="http://blog.hig.no/endnote/files/2010/06/import_filter-1024x430.jpg" alt="" width="1024" height="430" /></a> <a href="http://blog.hig.no/endnote/files/2010/06/import_filter.jpg"><br />
</a></p>
<p>Endrer du &#8220;Type of Article&#8221; til &#8220;{IGNORE}&#8221; vil daatene som ligger i dette feltet i importfila, bli oversett/ignorert ved importen. Husk å lagre fila under nytt navn hvis du bestemmer deg for å endre. Og &#8211; husk på å bruke det filteret du har endret neste gang du skal importere fra Medline via OvidSP!</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:3220:"<p>Selv om EndNote stadig vekk lanserer nye importfiltre, kan det likevel være nødvendig å gjøre endringer for å redusere &#8220;vaskingen&#8221; av importerte data. Etter at EndNote kom med oppdaterte versjoner av importfiltre for OVID-basene, fikk jeg lyst til å teste ut filteret for import av referanser fra Medline via Ovid. Etter å ha gjennomført en uproblematisk import fikk jeg dette resultatet i visningsstilen APA:</p>
<p>Barnard, A., Nash, R., &amp; O&#8217;Brien, M. (2005). Information literacy: developing lifelong skills through nursing education.  [Review]. <em>Journal of Nursing Education, 44</em>(11), 505-510.</p>
<p>I det store og hele ser jo dette fint ut, bortsett fra detaljen som sier at artikkelen er fagfellevurdert ([Review]). I EndNote kan dette filtreres ut på to måter – enten ved at du endrer i visningsstilen (out-put styles) slik at dataene i feltet ”Type of Article” ikke vises, eller ved at du endrer importfilteret slik at dataene som ligger i feltet ”Type of Article” ikke blir med når du foretar importen.</p>
<p>Om du velger den ene eller den andre metoden så må du vite at det valget du foretar har noen konsekvenser. Endrer du i visningsstilen vil dataene i feltet ”Type of Article” fortsatt være intakte i EndNote-biblioteket slik at du for eksempel senere kan søke fram ”Review-artiklene”. For å få dette riktig i forhold til APA-stilens krav (hvor dette normalt ikke skal vises), må du altså endre visningsstilen. Hvis du derimot fjerner dataene ved importen slik at du ikke trenger å endre visningsstilen, vil du naturligvis ikke kunne søke fram fagfellevurderte artikler hvis det er ønskelig. Har du heller ikke bruk for dette, kan du endre importfilteret slik at du får følgende resultat etter importen:</p>
<p>Barnard, A., Nash, R., &amp; O&#8217;Brien, M. (2005). Information literacy: developing lifelong skills through nursing education. <em>Journal of Nursing Education, 44</em>(11), 505-510.</p>
<p>Fremgangsmetoden er slik: Stå i EndNote og velg &lt;Edit&gt;, &lt;Import Filters&gt;, &lt;Open Filter Manager &#8230;&gt;. Finn fram til Medline-filteret fra OvidSP, marker det og klikk &#8220;Edit&#8221;. I vinduet du får opp velger du &#8220;Templates&#8221; i menyen til høyre, og her se du nå de ulike feltene som en importert post kan bestå av. Leter du nedover, kommer du etter hvert til et felt hvor taggen heter &#8220;PT &#8211; &#8221; med tilhørende &#8220;Field(s)&#8221; hvor det står &#8220;Type of Article&#8221;.</p>
<p><a href="http://blog.hig.no/endnote/files/2010/06/import_filter.jpg"><img class="aligncenter size-large wp-image-365" title="import_filter" src="http://blog.hig.no/endnote/files/2010/06/import_filter-1024x430.jpg" alt="" width="1024" height="430" /></a> <a href="http://blog.hig.no/endnote/files/2010/06/import_filter.jpg"><br />
</a></p>
<p>Endrer du &#8220;Type of Article&#8221; til &#8220;{IGNORE}&#8221; vil daatene som ligger i dette feltet i importfila, bli oversett/ignorert ved importen. Husk å lagre fila under nytt navn hvis du bestemmer deg for å endre. Og &#8211; husk på å bruke det filteret du har endret neste gang du skal importere fra Medline via OvidSP!</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:81:"http://blog.hig.no/endnote/2010/06/15/gj%c3%b8re-endringer-i-importfilteret/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:2;a:6:{s:4:"data";s:50:"
		
		
		
		
		
				
		
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:58:"Nye visningsstiler, importfiltre og “connection files”";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:111:"http://blog.hig.no/endnote/2010/06/15/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-17/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:120:"http://blog.hig.no/endnote/2010/06/15/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-17/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 15 Jun 2010 17:00:14 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:4:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:17:"connections files";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:12:"importfiltre";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:3;a:5:{s:4:"data";s:14:"visningsstiler";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:33:"http://blog.hig.no/endnote/?p=362";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1047:"<p>Thomson Reuters har lansert nye og oppdaterte visningsstiler, importfiltre og “connections files” til EndNote (<a href="http://www.endnote.com/pr-cont-may10.asp">http://www.endnote.com/pr-cont-may10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Du kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Visningsstilfilene (out-put styles) skal ned i mappa “Styles”, importfiltrene skal ned i mappa “Filters” mens “connections-filene” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows XP, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:1047:"<p>Thomson Reuters har lansert nye og oppdaterte visningsstiler, importfiltre og “connections files” til EndNote (<a href="http://www.endnote.com/pr-cont-may10.asp">http://www.endnote.com/pr-cont-may10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Du kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Visningsstilfilene (out-put styles) skal ned i mappa “Styles”, importfiltrene skal ned i mappa “Filters” mens “connections-filene” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows XP, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:116:"http://blog.hig.no/endnote/2010/06/15/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-17/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:3;a:6:{s:4:"data";s:47:"
		
		
		
		
		
				
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:34:"EndNote og Word 2010 kompatiblitet";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:73:"http://blog.hig.no/endnote/2010/06/15/endnote-og-word-2010-kompatiblitet/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:82:"http://blog.hig.no/endnote/2010/06/15/endnote-og-word-2010-kompatiblitet/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 15 Jun 2010 10:50:22 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:3:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:10:"EndNote X4";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:9:"Word 2010";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:33:"http://blog.hig.no/endnote/?p=360";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:448:"<p>EndNote x3 og tidligere versjoner av EndNote er ikke kompatible med Word 2010. Derfor vil EndNote X4 bli lansert i løpet av juni, på omtrent samme tid som Microsoft Office 2010 blir lansert. EndNote X4 skal altså fungere sammen med &#8220;Word 2010 32-bit”. Senere i år vil en gratis oppdatering kompatibel for &#8220;Word 2010 64 bit&#8221; bli gjort tilgjengelig. Denne gratis oppdateringen krever at programvaren din er registrert.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:448:"<p>EndNote x3 og tidligere versjoner av EndNote er ikke kompatible med Word 2010. Derfor vil EndNote X4 bli lansert i løpet av juni, på omtrent samme tid som Microsoft Office 2010 blir lansert. EndNote X4 skal altså fungere sammen med &#8220;Word 2010 32-bit”. Senere i år vil en gratis oppdatering kompatibel for &#8220;Word 2010 64 bit&#8221; bli gjort tilgjengelig. Denne gratis oppdateringen krever at programvaren din er registrert.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:78:"http://blog.hig.no/endnote/2010/06/15/endnote-og-word-2010-kompatiblitet/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"1";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:4;a:6:{s:4:"data";s:44:"
		
		
		
		
		
				
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:27:"Spekulasjoner om EndNote X4";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:66:"http://blog.hig.no/endnote/2010/06/13/spekulasjoner-om-endnote-x4/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:75:"http://blog.hig.no/endnote/2010/06/13/spekulasjoner-om-endnote-x4/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Sun, 13 Jun 2010 09:39:08 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:2:{i:0;a:5:{s:4:"data";s:13:"Uncategorized";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:10:"EndNote X4";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:66:"http://blog.hig.no/endnote/2010/06/13/spekulasjoner-om-endnote-x4/";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:705:"<p>I diverse sammenhenger dukker det opp spørsmål om hva EndNote X4 vil bringe av nyheter. De såkalte &#8220;beta-testerne&#8221; som er i gang med å prøve ut EndNote X4 har imidlertid inngått avtale om konfidensialitet med Thomson Reuter og kan følgelig ikke si noe som helst om hvilken ny funksjonalitet som kommer. Så, for alle som bekymrer seg for evt. kompatiblitetsproblemer og lignende, er det bare en ting å gjøre og det er å smøre seg med tålmodighet! Selv synes jeg EndNote X3 har vært den beste og mest stabile versjonen av EndNote, og av den grunn så er jeg noe skeptisk til hva som kommer. Men, endringer er det eneste sikre så det gjelder å henge seg på ferden videre!</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:705:"<p>I diverse sammenhenger dukker det opp spørsmål om hva EndNote X4 vil bringe av nyheter. De såkalte &#8220;beta-testerne&#8221; som er i gang med å prøve ut EndNote X4 har imidlertid inngått avtale om konfidensialitet med Thomson Reuter og kan følgelig ikke si noe som helst om hvilken ny funksjonalitet som kommer. Så, for alle som bekymrer seg for evt. kompatiblitetsproblemer og lignende, er det bare en ting å gjøre og det er å smøre seg med tålmodighet! Selv synes jeg EndNote X3 har vært den beste og mest stabile versjonen av EndNote, og av den grunn så er jeg noe skeptisk til hva som kommer. Men, endringer er det eneste sikre så det gjelder å henge seg på ferden videre!</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:71:"http://blog.hig.no/endnote/2010/06/13/spekulasjoner-om-endnote-x4/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:5;a:6:{s:4:"data";s:50:"
		
		
		
		
		
				
		
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:24:"Introduksjon til EndNote";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:63:"http://blog.hig.no/endnote/2010/06/04/introduksjon-til-endnote/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:72:"http://blog.hig.no/endnote/2010/06/04/introduksjon-til-endnote/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 04 Jun 2010 09:16:38 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:4:{i:0;a:5:{s:4:"data";s:10:"Opplæring";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:17:"instruksjonsvideo";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:16:"opplæringsvideo";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:3;a:5:{s:4:"data";s:5:"video";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:44:"http://endnoteinnlandet.wordpress.com/?p=353";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1409:"<p>Jeg har endelig fått lagt ut en kort videointroduksjon (ca. 5 min) for EndNote. Den er ment som en innledning for de som ønsker å lære seg EndNote, og jeg ber studenter og ansatte som skal ha opplæring i EndNote om å se gjennom videosnutten i forkant av opplæringen/kurset. Jeg har også laget tre deler til, men disse har jeg foreløpig valgt å ikke legge ut da jeg ikke er helt fornøyd med kvaliteten. Men studenter og ansatte som kommer på kurs i EndNote til høsten vil få utdelt en CD med hele videoopplæringen for EndNote. Gi meg gjerne tilbakemelding hvis du har forslag til forbedringer!</p>
<p><span class="youtube">
<object width="425" height="344">
<param name="movie" value="http://www.youtube.com/v/MrGgLnfQcE8&amp;rel=1&amp;color1=d6d6d6&amp;color2=f0f0f0&amp;border=0&amp;fs=1&amp;hl=en&amp;autoplay=0&amp;showinfo=0&amp;iv_load_policy=3&amp;showsearch=0" />
<param name="allowFullScreen" value="true" />
<embed wmode="transparent" src="http://www.youtube.com/v/MrGgLnfQcE8&amp;rel=1&amp;color1=d6d6d6&amp;color2=f0f0f0&amp;border=0&amp;fs=1&amp;hl=en&amp;autoplay=0&amp;showinfo=0&amp;iv_load_policy=3&amp;showsearch=0" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="344"></embed>
<param name="wmode" value="transparent" />
</object>
</span><p><a href="http://www.youtube.com/watch?v=MrGgLnfQcE8">www.youtube.com/watch?v=MrGgLnfQcE8</a></p></p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:1409:"<p>Jeg har endelig fått lagt ut en kort videointroduksjon (ca. 5 min) for EndNote. Den er ment som en innledning for de som ønsker å lære seg EndNote, og jeg ber studenter og ansatte som skal ha opplæring i EndNote om å se gjennom videosnutten i forkant av opplæringen/kurset. Jeg har også laget tre deler til, men disse har jeg foreløpig valgt å ikke legge ut da jeg ikke er helt fornøyd med kvaliteten. Men studenter og ansatte som kommer på kurs i EndNote til høsten vil få utdelt en CD med hele videoopplæringen for EndNote. Gi meg gjerne tilbakemelding hvis du har forslag til forbedringer!</p>
<p><span class="youtube">
<object width="425" height="344">
<param name="movie" value="http://www.youtube.com/v/MrGgLnfQcE8&amp;rel=1&amp;color1=d6d6d6&amp;color2=f0f0f0&amp;border=0&amp;fs=1&amp;hl=en&amp;autoplay=0&amp;showinfo=0&amp;iv_load_policy=3&amp;showsearch=0" />
<param name="allowFullScreen" value="true" />
<embed wmode="transparent" src="http://www.youtube.com/v/MrGgLnfQcE8&amp;rel=1&amp;color1=d6d6d6&amp;color2=f0f0f0&amp;border=0&amp;fs=1&amp;hl=en&amp;autoplay=0&amp;showinfo=0&amp;iv_load_policy=3&amp;showsearch=0" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="344"></embed>
<param name="wmode" value="transparent" />
</object>
</span><p><a href="http://www.youtube.com/watch?v=MrGgLnfQcE8">www.youtube.com/watch?v=MrGgLnfQcE8</a></p></p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:68:"http://blog.hig.no/endnote/2010/06/04/introduksjon-til-endnote/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:6;a:6:{s:4:"data";s:50:"
		
		
		
		
		
				
		
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:58:"Nye visningsstiler, importfiltre og “connection files”";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:111:"http://blog.hig.no/endnote/2010/05/25/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-16/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:120:"http://blog.hig.no/endnote/2010/05/25/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-16/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 25 May 2010 17:07:29 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:4:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:17:"connections files";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:12:"importfiltre";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:3;a:5:{s:4:"data";s:14:"visningsstiler";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:44:"http://endnoteinnlandet.wordpress.com/?p=350";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1052:"<p>Thomson Reuters har lansert nye og oppdaterte visningsstiler, importfiltre og “connections files” til EndNote (<a href="http://www.endnote.com/pr-cont-april10.asp">http://www.endnote.com/pr-cont-april10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Man kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Visningsstilfilene (out-put styles) skal ned i mappa “Styles”, importfiltrene skal ned i mappa “Filters” mens “connections-filene” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows XP, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:1052:"<p>Thomson Reuters har lansert nye og oppdaterte visningsstiler, importfiltre og “connections files” til EndNote (<a href="http://www.endnote.com/pr-cont-april10.asp">http://www.endnote.com/pr-cont-april10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Man kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Visningsstilfilene (out-put styles) skal ned i mappa “Styles”, importfiltrene skal ned i mappa “Filters” mens “connections-filene” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows XP, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:116:"http://blog.hig.no/endnote/2010/05/25/nye-visningsstiler-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d-16/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:7;a:6:{s:4:"data";s:44:"
		
		
		
		
		
				
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:53:"Visningsstiler for Høgskolen i Gjøvik i EndNote Web";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:100:"http://blog.hig.no/endnote/2010/05/18/visningsstiler-for-h%c3%b8gskolen-i-gj%c3%b8vik-i-endnote-web/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:109:"http://blog.hig.no/endnote/2010/05/18/visningsstiler-for-h%c3%b8gskolen-i-gj%c3%b8vik-i-endnote-web/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 18 May 2010 07:49:33 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:2:{i:0;a:5:{s:4:"data";s:10:"Opplæring";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:14:"visningsstiler";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:44:"http://endnoteinnlandet.wordpress.com/?p=344";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:617:"<p>Ved Høgskolen i Gjøvik, avdeling for helse, omsorg, sykepleie (HOS), benyttes en variant av Harvard når studentene leverer sine studentarbeider. Vi har laget en visningsstil for EndNote som er tilpasset <a href="http://www.hig.no/biblioteket/oppgaveskriving/harvard">avdelingens krav</a>, og nå er denne visningsstilen også tilgjengelig via EndNote Web hvis du er innlogget via HIGs pc-nettverk. Vi har kalt visningsstilene <em>HIG_Harvard</em> (norsk versjon) og <em>HIG_Harvard_english</em> (engelsk versjon), og du finner dem under <em>Format</em>, <em>Bibliography</em>, <em>Bibliographic style</em>.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:617:"<p>Ved Høgskolen i Gjøvik, avdeling for helse, omsorg, sykepleie (HOS), benyttes en variant av Harvard når studentene leverer sine studentarbeider. Vi har laget en visningsstil for EndNote som er tilpasset <a href="http://www.hig.no/biblioteket/oppgaveskriving/harvard">avdelingens krav</a>, og nå er denne visningsstilen også tilgjengelig via EndNote Web hvis du er innlogget via HIGs pc-nettverk. Vi har kalt visningsstilene <em>HIG_Harvard</em> (norsk versjon) og <em>HIG_Harvard_english</em> (engelsk versjon), og du finner dem under <em>Format</em>, <em>Bibliography</em>, <em>Bibliographic style</em>.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:105:"http://blog.hig.no/endnote/2010/05/18/visningsstiler-for-h%c3%b8gskolen-i-gj%c3%b8vik-i-endnote-web/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:8;a:6:{s:4:"data";s:44:"
		
		
		
		
		
				
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"Endringer i EndNote Web";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://blog.hig.no/endnote/2010/05/18/endringer-i-endnote-web/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:71:"http://blog.hig.no/endnote/2010/05/18/endringer-i-endnote-web/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 18 May 2010 07:05:09 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:2:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:11:"EndNote Web";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:44:"http://endnoteinnlandet.wordpress.com/?p=342";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:442:"<p>Thomson Reuters melder at det nylig ble gjort noen oppgraderinger i EndNote Web. Nå er det mulig å sortere referansene etter &#8220;times cited&#8221;, &#8220;date added&#8221; og &#8220;date modified&#8221;. Det er også mulig å se hvilken gruppetilhørighet de enkelte referansene har. Antallet referanser du kan overføre mellom EndNote Web og Endnote på pc&#8217;en er økt til 10 000.  Også lagringsfunksjonen er forbedret.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:442:"<p>Thomson Reuters melder at det nylig ble gjort noen oppgraderinger i EndNote Web. Nå er det mulig å sortere referansene etter &#8220;times cited&#8221;, &#8220;date added&#8221; og &#8220;date modified&#8221;. Det er også mulig å se hvilken gruppetilhørighet de enkelte referansene har. Antallet referanser du kan overføre mellom EndNote Web og Endnote på pc&#8217;en er økt til 10 000.  Også lagringsfunksjonen er forbedret.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:67:"http://blog.hig.no/endnote/2010/05/18/endringer-i-endnote-web/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:9;a:6:{s:4:"data";s:47:"
		
		
		
		
		
				
		
		

		
		
			
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:42:"Nye importfiltre og “connection files”";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:93:"http://blog.hig.no/endnote/2010/04/18/nye-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:102:"http://blog.hig.no/endnote/2010/04/18/nye-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Sun, 18 Apr 2010 16:55:44 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:3:{i:0;a:5:{s:4:"data";s:18:"Programoppdatering";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:17:"connections files";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:12:"importfiltre";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:44:"http://endnoteinnlandet.wordpress.com/?p=339";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:960:"<p>Thomson Reuters har lansert nye og oppdaterte importfiltre og “connection files” for EndNote (<a href="http://www.endnote.com/pr-cont-mar10.asp">http://www.endnote.com/pr-cont-mar10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Man kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Importfiltrene skal ned i mappa “Filters” mens “connections-files” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:12:"Klaus Jøran";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:960:"<p>Thomson Reuters har lansert nye og oppdaterte importfiltre og “connection files” for EndNote (<a href="http://www.endnote.com/pr-cont-mar10.asp">http://www.endnote.com/pr-cont-mar10.asp</a>). Sørg for å ta kopi av filene som er viktige og lagre dem med et genuint navn. De nye filene vil nemlig overskrive eldre filer med samme filnavn.</p>
<p>Man kan laste ned individuelle filer eller “hele pakka”. Filene kommer i form av en ZIP-fil. Når ZIP-fila er lastet ned til pc’en/mac’en, må man pakke ut og legge filene til riktig mappe i EndNote-katalogen. Importfiltrene skal ned i mappa “Filters” mens “connections-files” skal ned i mappa “Connections”. EndNote-mappene ligger som regel på C:\Program Files\EndNote hvis du bruker Windows, eller eller Harddrive:Applications:EndNote hvis du bruker Mac OS X.</p>
<p>Husk at EndNote blir tregere hvis du laster inn alle filene. Last derfor bare ned de filene du virkelig trenger.</p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:98:"http://blog.hig.no/endnote/2010/04/18/nye-importfiltre-og-%e2%80%9cconnection-files%e2%80%9d/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:4:"href";s:32:"http://blog.hig.no/endnote/feed/";s:3:"rel";s:4:"self";s:4:"type";s:19:"application/rss+xml";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:44:"http://purl.org/rss/1.0/modules/syndication/";a:2:{s:12:"updatePeriod";a:1:{i:0;a:5:{s:4:"data";s:6:"hourly";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:15:"updateFrequency";a:1:{i:0;a:5:{s:4:"data";s:1:"1";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}}}}}}s:4:"type";i:128;s:7:"headers";a:9:{s:4:"date";s:29:"Thu, 17 Jun 2010 08:24:43 GMT";s:6:"server";s:21:"Apache/2.2.3 (CentOS)";s:12:"x-powered-by";s:9:"PHP/5.1.6";s:10:"x-pingback";s:37:"http://blog.hig.no/endnote/xmlrpc.php";s:13:"last-modified";s:29:"Wed, 16 Jun 2010 20:28:08 GMT";s:4:"etag";s:32:"0a85fbb4cb53328c47389e737d1186d0";s:10:"connection";s:5:"close";s:17:"transfer-encoding";s:7:"chunked";s:12:"content-type";s:23:"text/xml; charset=UTF-8";}s:5:"build";s:14:"20091211203510";}